---

# Group vars for RPI cluster

rpi_domain: "{{ allconf.rpi_cluster.domain }}"

# RPI exporter user and group variables
rpi_exporter_group: "rpi_exporter"
rpi_exporter_user: "rpi_exporter"

# Node exporter user and group varaibles
node_exporter_group: "node_exporter"
node_exporter_user: "node_exporter"

# Prometheus user and group variables
prometheus_user: "prometheus"
prometheus_group: "prometheus"

# RPI exporter source
rpi_exporter_source: "https://github.com/lukasmalkmus/rpi_exporter/releases/download/v0.6.0/rpi_exporter-0.6.0.linux-armv7.tar.gz"

# Node exporter source
node_exporter_source: "https://github.com/prometheus/node_exporter/releases/download/v1.0.0/node_exporter-1.0.0.linux-armv7.tar.gz"

# Prometheus source
prometheus_source: "https://github.com/prometheus/prometheus/releases/download/v2.18.1/prometheus-2.18.1.linux-armv7.tar.gz"

# Prometheus data directory and config directory
prometheus_data_dir: "/data/prometheus"
prometheus_config_dir: "/etc/prometheus"


...
