# Ansible host vars for RPI-04
---
ansible_host: "{{ allconf.rpi_cluster.hosts.rpi_04.ip_address }}"
ansible_hostname: "{{ allconf.rpi_cluster.hosts.rpi_04.hostname }}"
ansible_fqdn: "{{ allconf.rpi_cluster.hosts.rpi_04.hostname }}.{{ rpi_domain }}"
ansible_cname: "{{ allconf.rpi_cluster.hosts.rpi_04.cname }}"

...
